### ISSUE TITLE
Replacer Ammends New Transform instead of Modifying it

### ISSUE THREAD

**Issue by DigiWorm0** [nesrak1/AssetsTools.NET#28] opened 2020-12-30 20:44 UTC
I have the following code that is intended to remove a child from a father transform.

```C#
// Import
AssetsManager assetsManager = new AssetsManager();
List<AssetsReplacer> replacers = new List<AssetsReplacer>();
assetsManager.LoadClassPackage("classdata.tpk");
AssetsFileInstance assetsFileInstance = assetsManager.LoadAssetsFile("sharedassets0.assets", false);
assetsManager.LoadClassDatabaseFromPackage(assetsFileInstance.file.typeTree.unityVersion);
AssetsFileTable assetsFileTable = assetsFileInstance.table;

// Get Father
long fatherID = 16256;
long childID = 16153;
AssetFileInfoEx fatherFile = assetsFileTable.GetAssetInfo(fatherID);
AssetTypeValueField fatherBaseField = assetsManager.GetTypeInstance(assetsFileInstance.file, fatherFile).GetBaseField();

// Clear Father's Child
AssetTypeValueField[] fatherChildren = fatherBaseField.Get("m_Children").Get("Array").children;
AssetTypeValueField[] newChildren = fatherChildren.Where(child => child.Get("m_PathID").GetValue().AsInt64() != childID).ToArray();
fatherBaseField.Get("m_Children").Get("Array").SetChildrenList(newChildren);

// Save
replacers.Add(new AssetsReplacerFromMemory(0, fatherFile.index, (int)fatherFile.curFileType, 0xFFFF, fatherBaseField.WriteToByteArray()));

// Export
AssetsFileWriter writer = new AssetsFileWriter(File.OpenWrite("sharedassets0-new.assets"));
assetsFileInstance.file.Write(writer, 0, replacers, 0);
writer.Close();
```
However, **instead of editing the existing father transform, the replaces amend a new transform** so I end up with 2 transforms of the same ID (according to AssetsView). What am I missing here? In addition, I also update child's m_Father, I can upload that too if needed. Also, when viewing the transform, AssetsView claims the child has not been removed, but I think it is referencing the older transform and not the one I ammended.

I am using AssetsTools Update 15 v2.0.6 in .NET Framework v4.7.2.

**Comment by nesrak1** [comment] 2020-12-30 22:03
I was able to remove the child fine with your code above and when I added father remove code, it correctly showed the child as a root object in AssetsView. I also wasn't able to get assets with the same id either, it correctly overwrote the original asset.

**Comment by DigWorm0** [comment] 2020-12-31 05:20
Here is the function the code is pulled from:
```C#
private void EditExistingAsset(LIMapAsset asset, AssetTypeValueField spriteBaseField)
{
    Log("Editing Existing Asset " + asset.type);

    // Get and Clear Child's Father
    AssetExternal compAE = GetComponents(spriteBaseField);
    AssetTypeValueField compBaseField = compAE.instance.GetBaseField();

    long fatherID = compBaseField.Get("m_Father").Get("m_PathID").GetValue().AsInt64();
    compBaseField.Get("m_Father").Get("m_PathID").GetValue().Set(16553);
    AssetFileInfoEx fatherFile = assetsFileTable.GetAssetInfo(fatherID);
    AssetTypeValueField fatherBaseField = assetsManager.GetTypeInstance(assetsFileInstance.file, fatherFile).GetBaseField();

    // Get and Clear Father's Child
    AssetTypeValueField[] fatherChildren = fatherBaseField.Get("m_Children").Get("Array").GetChildrenList();
    AssetTypeValueField[] newChildren = fatherChildren.Where(child => child.Get("m_PathID").GetValue().AsInt64() != compAE.info.index).ToArray();
    fatherBaseField.Get("m_Children").Get("Array").SetChildrenList(newChildren);

    replacers.Add(new AssetsReplacerFromMemory(0, fatherFile.index, (int)fatherFile.curFileType, 0xFFFF, fatherBaseField.WriteToByteArray()));

    // Get and Set New Father
    AssetTypeValueField newChild = ValueBuilder.DefaultValueFieldFromArrayTemplate(polusCompBaseField.Get("m_Children").Get("Array"));
    newChild.Get("m_FileID").GetValue().Set(0);
    newChild.Get("m_PathID").GetValue().Set(compAE.info.index);
    polusCompBaseField.Get("m_Children").Get("Array").SetChildrenList(polusCompBaseField.Get("m_Children").Get("Array").children.Concat(new List<AssetTypeValueField>() { newChild }).ToArray());

    // Set Transform
    compBaseField.Get("m_LocalPosition").Get("x").GetValue().Set(asset.x);
    compBaseField.Get("m_LocalPosition").Get("y").GetValue().Set(asset.y);
    compBaseField.Get("m_LocalPosition").Get("z").GetValue().Set(asset.z);
    compBaseField.Get("m_LocalScale")   .Get("x").GetValue().Set(asset.xScale);
    compBaseField.Get("m_LocalScale")   .Get("y").GetValue().Set(asset.yScale);
    compBaseField.Get("m_LocalScale")   .Get("z").GetValue().Set(1);
    compBaseField.Get("m_LocalRotation").Get("z").GetValue().Set(asset.zRotate);
    compBaseField.Get("m_LocalRotation").Get("w").GetValue().Set(1);

    replacers.Add(new AssetsReplacerFromMemory(0, compAE.info.index, (int)compAE.info.curFileType, 0xFFFF, compBaseField.WriteToByteArray()));
}
```
Where LIMapAsset is an object with a name, type, x, y, z, xScale, yScale, and zRotate. Then, the file is later saved using this function:
```C#
public int Export()
{
    try
    {
        Log("Exporting...");

        // File
        if (File.Exists(assetsLocation))
            File.Delete(assetsLocation);
        if (File.Exists(custAssetsLocation))
            File.Delete(custAssetsLocation);

        // Polus
        replacers.Add(new AssetsReplacerFromMemory(0, polusCompAsset.index, (int)polusCompAsset.curFileType, 0xFFFF, polusCompBaseField.WriteToByteArray()));

        // Writer
        AssetsFileWriter writer = new AssetsFileWriter(File.OpenWrite(assetsLocation));
        assetsFileInstance.file.Write(writer, 0, replacers, 0);
        writer.Close();

        // Custom Asset Writer
        File.WriteAllBytes(custAssetsLocation, customAssetBytes.ToArray());
        return 0;
    }
    catch (IOException ex)
    {
        return 3;
    }
}
```
The full repository is also available [here](https://github.com/DigWorm0/LevelImposter). (It is intended to be a custom Among Us map maker, when complete)

**Comment by nesrak1** [comment] 2020-12-31 18:34
I tried this code on among us mobile, replacing `16553` with `polusCompAsset` (just in general, would recommend not hardcoding your pathids because they can change between platforms and updates) and I was able to get it working fine still. I'm guessing the issue is somewhere else in your code. Also, which assets are being duplicated, or are they all being duplicated? Do they show next to each other in AssetsView or is the duplicate asset at the very end of the file?

I would prefer a minimum working example of the bug like the first bit of code you posted that you can confirm this problem happens with (including which specific assets (by name) you used). I've attached the code I used so you can try what I tested.
[Issue28.zip](https://github.com/nesrak1/AssetsTools.NET/files/5758034/Issue28.zip)

**Comment by DigWorm0** [comment] 2020-12-31 19:22
**On unity 2019.4, is pc on this also?**
Indeed they are

**Which assets are being duplicated, or are they all being duplicated? Do they show next to each other in AssetsView or is the duplicate asset at the very end of the file?**
The transform of the father asset is being duplicated to the end of the file. The transform at the end of the file removes the child while the original transform still has the child.
<img width="288" alt="transform-2" src="https://user-images.githubusercontent.com/10067568/103422914-73b7b280-4b69-11eb-8d09-6cf3ad261090.PNG">
<img width="290" alt="transform-1" src="https://user-images.githubusercontent.com/10067568/103422908-70bcc200-4b69-11eb-88ee-be39190e4121.PNG">

Thank you for your continued assistance on this issue. I'll continue to debug this issue and post a solution here if I can find it.

**Comment by nesrak1** [comment] 2021-05-17 19:39
Closing this issue since I wasn't able to reproduce, and you aren't using this anymore.
I suspect the problem was that you had added two replacers of the same pathId, one with the original bytes and one with the new bytes. When you have two replacers, it will only replace one then append the second one to the end.

**Closed by nesrak1** 2021-05-17 19:39 UTC
