### ISSUE TITLE
[Bug] The stream of LZMA is not set up correctly

### ISSUE THREAD

**Issue by HKLab** [nesrak1/AssetsTools.NET#94] opened 2023-02-14 15:08 UTC
I used LoadBundleFile to load an AssetsBundle that was compressed using LAMZ

The code looks like this
![image](https://user-images.githubusercontent.com/60681033/218776629-b18c9bd7-c2ab-4d00-97dc-74b83703ff04.png)

When I try to get Assets using LoadAssetsFileFromBundle, it tells me to read more than the stream size.

I found that the underlying stream used by Reader is the original FileStream rather than the decompressed MemoryStream.

![image](https://user-images.githubusercontent.com/60681033/218777440-00595412-76f8-43a6-a0c6-780cbe761165.png)

**Comment by nesrak1** [comment] 2023-02-14 17:39
I thought I fixed this already since I had a convo about it in the discord. The issue is that the code to check LZMA does it by checking the header compression format instead of the block compression format. When I get back home, I'll check if it's just something I committed but didn't push.

**Comment by nesrak1** [comment] 2023-02-14 20:23
Check latest commit.

**Closed** 2023-02-15 04:32 UTC
